apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgen
  namespace: deploytracker
  labels:
    app.kubernetes.io/name: loadgen
    app.kubernetes.io/instance: deploytracker
    app.kubernetes.io/version: "0.1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: loadgen
      app.kubernetes.io/instance: deploytracker
  template:
    metadata:
      labels:
        app.kubernetes.io/name: loadgen
        app.kubernetes.io/instance: deploytracker
    spec:
      nodeSelector:
        role: app
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ecr-credentials
      containers:
        - name: loadgen
          image: 378202225330.dkr.ecr.eu-west-3.amazonaws.com/deploytracker-loadgen:latest
          imagePullPolicy: Always
          env:
            - name: DEPLOYTRACKER_API_URL
              value: "http://deploytracker.deploytracker.svc.cluster.local:8000"
            - name: LOADGEN_INTERVAL_SECONDS
              value: "10"
            - name: LOADGEN_FAILURE_RATE
              value: "0.15"
            - name: DEPLOYTRACKER_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: deploytracker-secrets
                  key: DEPLOYTRACKER_ADMIN_USERNAME
            - name: DEPLOYTRACKER_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: deploytracker-secrets
                  key: DEPLOYTRACKER_ADMIN_PASSWORD
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
