apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: observability
  labels:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: otel-collector
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: otlp-grpc
      protocol: TCP
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      protocol: TCP
      port: 4318
      targetPort: otlp-http
