from datetime import datetime
from typing import Protocol
from uuid import UUID

from .models import Deployment, Service


class DeploymentRepository(Protocol):
    def save(self, deployment: Deployment) -> Deployment: ...
    def get(self, deployment_id: UUID) -> Deployment | None: ...
    def list_by_service(self, service: str, since: datetime) -> list[Deployment]: ...
    def update(self, deployment: Deployment) -> Deployment: ...


class ServiceRepository(Protocol):
    def save(self, service: Service) -> Service: ...
    def get(self, name: str) -> Service | None: ...
    def list_all(self) -> list[Service]: ...


class Clock(Protocol):
    def now(self) -> datetime: ...
