---
- name: Fetch kubeconfig from K3s server
  hosts: k3s_server
  tasks:
    - name: Fetch kubeconfig
      fetch:
        src: /etc/rancher/k3s/k3s.yaml
        dest: /tmp/k3s-kubeconfig.yaml
        flat: true

    - name: Replace server URL with public IP
      delegate_to: localhost
      replace:
        path: /tmp/k3s-kubeconfig.yaml
        regexp: "https://127.0.0.1:6443"
        replace: "https://{{ ansible_host }}:6443"

    - name: Copy kubeconfig to default location
      delegate_to: localhost
      copy:
        src: /tmp/k3s-kubeconfig.yaml
        dest: ~/.kube/config
        mode: "0600"
